#+title: Short Selling Stock
#+author: Matt Brigida, Ph.D.
#+STARTUP: hideblocks
#+PROPERTY: header-args :results output :exports both
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup


** Why Short Stock?

By shorting stock we profit when the stock price declines.  So you can use short sales to speculate.

However, shorting stock is also used by banks to hedge put options they have sold, as well as other derivative positions.

In other words, shorting stock is used to lessen the risk taken by banks and other financial intermediaries.  In fact, without the ability to short, put options and other derivatives may not exist. 

 

** So How Does It Work?

To short a share of stock, you borrow the stock from someone (say, Bob) and sell it to someone else (say, Sandra).  Say that you sold it to Sandra for \$100.  The cash balance in your account will increase by \$100, and you will hold a -1 position in the stock.  

-  Eventually, you'll have to return the stock to Bob to close our your short position.

-  To return the stock to Bob, you'll go to the market and buy a share.  You can buy it from anyone, not just Sandra.

 

** Example Profit/Loss

Imagine that the stock is trading in the market for \$80 when you decide to close the position.

-  To close the postion, you buy the stock for \$80 and return it to Bob.

-  After the transaction you are left with a profit of \$100 - \$80 = \$20.

 

** Example Profit/Loss

Alternatievly, say the stock is trading in the market for \$110 when you decide to close the position.

-  To close the postion, you buy the stock for \$110 and return it to Bob.

-  So you sold the stock for \$100, and bought it for \$110, for a loss of \$10.

 

**  Interactive App

On the next slide you can input the amount of shares you want to short, as well as the prices at which you open and close the short position.

-  The app shows each transaction made in the course of the short sale and also your ultimate profit.

-  A negative profit is a loss.

-  Complete lines open the short position, and dotted lines close the short.


#+BEGIN_EXPORT html
<script>
var calculate = function() {

  var pp = Number(document.getElementById("pp").value);
  var n = Number(document.getElementById("n").value);
  var im = Number(document.getElementById("im").value);
  var cp = Number(document.getElementById("cp").value);
  
  var loan = pp * n * (1 - im);
  var new_margin = 100 * (cp * n - loan) / (cp * n);
  
  document.getElementById("out_new_margin").innerHTML = new_margin.toFixed(2);

}
</script>


<body class="all">
  <h3>
    Long Margin Percent Calculator
  </h3>

  <div class="row">

    <div class="column">
      <table style="width:100%">
        <tr>
          <th align="left">Purchase Price:</th>
          <th><input id="pp" value="100" style="width: 50px"></th>
        </tr>
        <tr>
          <th align="left">Number of Shares:</th>
          <th><input id="n" value="100" style="width: 50px"></th>
        </tr>
        <tr>
          <th align="left">Initial Margin:</th>
          <th><input id="im" value="0.6" style="width: 50px"></th>
        </tr>
        <tr>
          <th align="left">Current Price:</th>
          <th><input id="cp" value="70" style="width: 50px"></th>
        </tr>
      </table>
      <button onclick="calculate()">
        Calculate.
      </button>
    </div>

    <div class="column">
    <p><b>Current Margin: <span id="out_new_margin"></span>%</b></p>
    </div>

  </div>
  <br>
  <br>
  <br>
</body>
#+END_EXPORT
 

** How Do You Borrow Shares?

This is handled by your broker -- you don't have to worry about the mechanics behind the scenes.

-  Essentially what happens is you broker will borrow the shares from a large investor or mutual fund.

-  Sometimes your broker doesn't think it will be able to borrow shares, and will indicate the stock is not available for shorting.

-  Note, you don't have any sort of right to short, and so during times of market turbulence, you may not be able to short many stocks.  

 

** Naked Shorting

Your broker has some leeway in terms of how soon they have to borrow shares -- generally, a few days.

-  In the past, however, some brokers never bothered to borrow the shares.

-  The term for shorting while failing to borrow the stock is 'Naked Shorting' and it has been banned by the U.S. Securities and Exchange Commission.

 

**  Alternatives to Shorting: Inverse ETFs

If you don't want to short (or your brokerage account doesn't allow it), you can simply buy an inverse [Exchange Traded Fund (ETF)](http://www.5minutefinance.org/concepts/exchange-traded-funds).

-  Buying an inverse ETF on a portfolio will afford a return very similar to shorting the portfolio.

-  Inverse ETFs are not available for individual stocks.

 

** Inverse ETF Performance

The next slide shows the performance of an ETF on the S&P 500 (SPY) and an inverse ETF on the S&P 500 (SH).

-  To zoom in or focus on a subinterval, use the range selector at the bottom of the chart.

-  You can see the inverse ETF (short) is a mirror image of the performance of the S&P 500.

 

** S&P 500 (SPY) and Short S&P 500 (SH)

```{r, echo=FALSE, message=FALSE, warning=FALSE}
#{{{
library(dygraphs)
devtools::install_github("joshuaulrich/quantmod", ref="157_yahoo_502")
library(quantmod)
renderDygraph({
    stock1 <- getSymbols("SPY", from = "1950-01-03", auto.assign = FALSE)
    stock2 <- getSymbols("SH", from = "1950-01-03", auto.assign = FALSE)
    stocks <- merge.xts(Ad(stock1), Ad(stock2), join = "inner")
    dygraph(Ad(stocks), main = "") %>%
        dyRangeSelector()
})
#}}}
```

 


<!---
** Does Shorting Create Shares?

Short answer: No.

In our example, Bob ownes a share, we *owe* one share, and Sandra ownes a share.  The number of shares outstanding are 1 - 1 + 1 = 1.

-  So as long as the shares are actually borrowed (it is not a naked short), shorting has no effect on the float.
-->

